# Generated by Django 4.1.dev20211027104129 on 2021-11-11 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('nome', models.CharField(max_length=200)),
                ('rg', models.BigIntegerField(default=0)),
                ('cpf', models.BigIntegerField(default=0)),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.IntegerField(default=0)),
                ('bairro', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
                ('usuario', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('codigo', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('nome', models.CharField(max_length=200)),
                ('insc_est', models.BigIntegerField(default=0)),
                ('cnpj', models.BigIntegerField(default=0)),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.IntegerField(default=0)),
                ('bairro', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
                ('usuario', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('codigo', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('veiculo', models.CharField(max_length=200)),
                ('capacidade', models.IntegerField(default=0)),
                ('moveis', models.BooleanField()),
                ('eletro', models.BooleanField()),
                ('metais', models.BooleanField()),
                ('alvenaria', models.BooleanField()),
                ('madeiramento', models.BooleanField()),
                ('troncos', models.BooleanField()),
                ('arbusto', models.BooleanField()),
                ('grama', models.BooleanField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportes', to='app_principal.prestador')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('codigo', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('quantidade', models.IntegerField(default=0)),
                ('moveis', models.BooleanField()),
                ('eletro', models.BooleanField()),
                ('metais', models.BooleanField()),
                ('alvenaria', models.BooleanField()),
                ('madeiramento', models.BooleanField()),
                ('troncos', models.BooleanField()),
                ('arbusto', models.BooleanField()),
                ('grama', models.BooleanField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratante', to='app_principal.cliente')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratado', to='app_principal.transporte')),
            ],
        ),
    ]
