# Generated by Django 4.1.dev20211027104129 on 2021-11-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('codigo', 'cpf', 'usuario'), name='cliente_unique'),
        ),
        migrations.AddConstraint(
            model_name='prestador',
            constraint=models.UniqueConstraint(fields=('codigo', 'cnpj', 'usuario'), name='prestador_unique'),
        ),
    ]
